kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
     uri: 'https://github.com/vbg/do400-greeting-console'
     ref: main
  output:
    to:
      kind: DockerImage
      name: quay.io/varadg/greeting-console
    pushSecret:
      name: my-quay-credentials
